# Numpy

## 1.1 Array

### 1.1.1 Inisiasi Array

In [1]:
'inisiasi list'
lst1 = [1,2,3]
lst1

[1, 2, 3]

In [ ]:
import numpy as np

In [9]:
'inisiasi array'
arr = np.array(lst1)
arr

array([1, 2, 3])

In [6]:
lst2 = [[30,60,90,27],
        [50,87,58,65],
        [14,25,15,8 ],
        [11,52,63,89]]

In [7]:
arr = np.array(lst2)
arr

array([[30, 60, 90, 27],
       [50, 87, 58, 65],
       [14, 25, 15,  8],
       [11, 52, 63, 89]])

In [10]:
'menggunakan linspace'
arr=np.linspace(0,10,5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [11]:
'menggunakan arange'
arr=np.arange(10,20,2)
arr

array([10, 12, 14, 16, 18])

In [12]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [13]:
np.arange(1,100,21)

array([ 1, 22, 43, 64, 85])

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
'Array reshape'
lst = [[30,60,90,27],
       [50,87,58,65],
       [14,25,15,8 ],
       [11,52,63,89]]

In [20]:
arr = np.array(lst)
arr

array([[30, 60, 90, 27],
       [50, 87, 58, 65],
       [14, 25, 15,  8],
       [11, 52, 63, 89]])

In [21]:
arr.reshape(2,8)

array([[30, 60, 90, 27, 50, 87, 58, 65],
       [14, 25, 15,  8, 11, 52, 63, 89]])

In [27]:
arr.reshape(4,4)

array([[30, 60, 90, 27],
       [50, 87, 58, 65],
       [14, 25, 15,  8],
       [11, 52, 63, 89]])

In [28]:
arr.reshape(1,16)

array([[30, 60, 90, 27, 50, 87, 58, 65, 14, 25, 15,  8, 11, 52, 63, 89]])

In [29]:
arr.reshape(16,1)

array([[30],
       [60],
       [90],
       [27],
       [50],
       [87],
       [58],
       [65],
       [14],
       [25],
       [15],
       [ 8],
       [11],
       [52],
       [63],
       [89]])

In [30]:
arr.reshape(2,-1)

array([[30, 60, 90, 27, 50, 87, 58, 65],
       [14, 25, 15,  8, 11, 52, 63, 89]])

In [32]:
arr.reshape(-1,2)
#-1 = 8

array([[30, 60],
       [90, 27],
       [50, 87],
       [58, 65],
       [14, 25],
       [15,  8],
       [11, 52],
       [63, 89]])

## 1.1.2 Menambahkan Data dan Mengupdate Data Pada Array

In [35]:
arr=np.arange(1,10)

In [37]:
arr[0]

1

In [39]:
arr[0]=100

In [47]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 15, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [41]:
arr=np.arange(1,25)

In [42]:
arr[10]

11

In [43]:
arr[10]=15

In [44]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 15, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [45]:
np.append(arr,arr,axis=0)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 15, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
       15, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

### 1.1.3 Mencari informasi Descriptive Statistic dari Array

In [48]:
lst =  [[30,60,90,27],
        [50,87,58,65],
        [14,25,15,8 ],
        [11,52,63,89]]

In [49]:
np.max(lst), np.min(lst), np.mean(lst), np.median(lst), np.percentile(lst, 10), np.std(lst)

(90, 8, 46.5, 51.0, 12.5, 27.631503759296198)

In [51]:
np.min(lst)

8

### 1.1.4 Slicing Array

indexing dalam array serupa dengan cara indexing pada list, dengan menggunakan [a:b:c]. Dimana:

a: inisiasi
b: akhir
c: steps

In [53]:
'slicing pada 1d array'
arr=np.array([0,9,8,7,6,5,4,3,2,1])

In [54]:
arr[3:7]

array([7, 6, 5, 4])

In [55]:
arr[3:-1]

array([7, 6, 5, 4, 3, 2])

In [56]:
arr[3:]

array([7, 6, 5, 4, 3, 2, 1])

In [57]:
arr[:]

array([0, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [58]:
arr[::2]

array([0, 8, 6, 4, 2])

In [59]:
arr[3:-2]

array([7, 6, 5, 4, 3])

In [60]:
arr[3:0]

array([], dtype=int32)

In [61]:
'slicing pada 2d array'
arr  =  np.array([[30,60,90,27],
                  [50,87,58,65],
                  [14,25,15,8 ],
                  [11,52,63,89]])

In [62]:
arr[0]

array([30, 60, 90, 27])

In [63]:
arr[1]

array([50, 87, 58, 65])

In [64]:
arr[0,2]

90

In [65]:
arr[3,2]

63

In [66]:
arr[0,1:4]

array([60, 90, 27])

In [67]:
arr[0:3]

array([[30, 60, 90, 27],
       [50, 87, 58, 65],
       [14, 25, 15,  8]])

In [68]:
arr[0:0]

array([], shape=(0, 4), dtype=int32)

In [69]:
arr[0:1]

array([[30, 60, 90, 27]])

In [70]:
arr[1,0]

50

In [71]:
arr[1:0]

array([], shape=(0, 4), dtype=int32)

In [72]:
arr[1:1]

array([], shape=(0, 4), dtype=int32)

In [73]:
arr[0:3,2]

array([90, 58, 15])

### 1.1.5 Arithmetic Matrix Operation

In [74]:
'''Operasi dengan menggunakan list'''
x = [30,60,90,270]

In [75]:
x + x

[30, 60, 90, 270, 30, 60, 90, 270]

In [76]:
'''Operasi dengan menggunakan array'''
x = np.array([30,60,90,270]) # creating array

In [77]:
x + x

array([ 60, 120, 180, 540])

In [78]:
np.sin(x)

array([-0.98803162, -0.30481062,  0.89399666, -0.17604595])

### 1.1.6 Matrix Operation

In [79]:
arr=np.arange(1,5)
arr

array([1, 2, 3, 4])

In [82]:
arr*arr

array([ 1,  4,  9, 16])

In [83]:
arr*arr*arr

array([ 1,  8, 27, 64])

In [ ]:
arr6=arr3*arr3
arr6

In [88]:
arr1 = np.reshape(arr,(1,-1))
arr2 = np.reshape(arr,(-1,1))*2

In [89]:
arr1

array([[1, 2, 3, 4]])

## 1.2 Random Number Generator 

numpy dapat membuat random number dengan berbagai model distribution. diantaranya:

-Normal distribution np.random.normal()
-Log normal np.random.lognormal()
-Triangle distribution np.random.triangular()
-exponential np.random.exponential()
dan model lannya..

In [91]:
np.random.normal()

-0.6296269838697416

In [92]:
np.random.triangular(10,14,19)

12.295131502263771

In [93]:
'''creating array with random number'''
np.random.normal(size=(10,2))

array([[-0.30549046, -0.61221408],
       [-0.84551115, -0.46366756],
       [-1.7025263 ,  0.1983937 ],
       [-1.59343162,  1.78723251],
       [ 1.20836972,  0.48837414],
       [ 0.67672682,  0.03499642],
       [ 0.82034359, -0.49290507],
       [ 0.88214785,  0.24475222],
       [ 0.03508447, -1.19285227],
       [ 0.94655282,  2.04335627]])

In [94]:
np.random.normal(size=(1,3))

array([[-0.86494294,  0.36886713,  0.29597521]])

In [95]:
np.random.normal(size=(4,3))

array([[-0.27384855, -0.36622312, -0.21155131],
       [-1.97488662,  1.17536781,  0.66620572],
       [ 0.03893933,  1.21377586,  0.39181766],
       [ 1.89879533, -0.65197345, -0.48949291]])

## 1.3 Numpy Math

Numpy math adalah sub package yang dapat digunakan untuk mempermudah melakuakn perhitungan saintifik. Beberapa contoh fungsi yang disajikan oleh numpy Math adalah:

Trigonomeri (np.sin(), np.con(), np.tan(), np.arcsin(), np.radians(), np.degrees() dll..)
Logaritmik (np.log())
Operasi akar (np.sqrt())

In [96]:
np.math.sin(90)

0.8939966636005579

In [97]:
np.sin(45)

0.8509035245341184

In [98]:
np.sin(30)

-0.9880316240928618

In [99]:
np.sin(90)

0.8939966636005579

In [100]:
np.radians(90)

1.5707963267948966

In [101]:
np.radians(45)

0.7853981633974483

In [103]:
np.sin(np.radians(90))

1.0

In [104]:
np.sin(np.radians(30))

0.49999999999999994

In [105]:
np.cos(np.radians(60))

0.5000000000000001

In [106]:
np.degrees(90)

5156.620156177409

# PANDAS

In [107]:
import pandas as pd

### 2.1.1 Membuat DataFrame dari list

In [114]:
data=np.random.normal(size=10)

In [115]:
data

array([-0.5123818 ,  1.78210501, -0.40125352, -1.47769514,  0.70723062,
        0.38046536,  0.59056123,  0.29881016,  1.24118948, -0.08972294])

In [116]:
# data = [1,2,3,2,3,4]  #===========> list or set or tuple
df = pd.DataFrame(data = zip(range(len(data)), data, data), columns = ['urutan', 'dummy 1', 'dummy 3'])

# data => list of list
# columns => list of texts

In [117]:
df

urutan   dummy 1   dummy 3
0       0 -0.512382 -0.512382
1       1  1.782105  1.782105
2       2 -0.401254 -0.401254
3       3 -1.477695 -1.477695
4       4  0.707231  0.707231
5       5  0.380465  0.380465
6       6  0.590561  0.590561
7       7  0.298810  0.298810
8       8  1.241189  1.241189
9       9 -0.089723 -0.089723

In [118]:
df = pd.DataFrame(data = zip(range(len(data)), data, data), columns = ['urutan', 'dummy 1', 'dummy 3'])

In [119]:
ab

urutan   dummy 1   dummy 3
0       0 -0.512382 -0.512382
1       1  1.782105  1.782105
2       2 -0.401254 -0.401254
3       3 -1.477695 -1.477695
4       4  0.707231  0.707231
5       5  0.380465  0.380465
6       6  0.590561  0.590561
7       7  0.298810  0.298810
8       8  1.241189  1.241189
9       9 -0.089723 -0.089723

In [125]:
df=pd.DataFrame(data=zip(range(len(data)), data, data),columns=['urutan','d','e'])

In [126]:
df

urutan         d         e
0       0 -0.512382 -0.512382
1       1  1.782105  1.782105
2       2 -0.401254 -0.401254
3       3 -1.477695 -1.477695
4       4  0.707231  0.707231
5       5  0.380465  0.380465
6       6  0.590561  0.590561
7       7  0.298810  0.298810
8       8  1.241189  1.241189
9       9 -0.089723 -0.089723

### 2.1.2 Membuat DataFrame dari Dict

In [129]:
data={'country':['belgia','indo','singapo'],'capital':['brussels','jkt','singapo'],'population':['3','5','2']}

In [130]:
data

{'country': ['belgia', 'indo', 'singapo'],
 'capital': ['brussels', 'jkt', 'singapo'],
 'population': ['3', '5', '2']}

In [131]:
df=pd.DataFrame(data)

In [132]:
data

{'country': ['belgia', 'indo', 'singapo'],
 'capital': ['brussels', 'jkt', 'singapo'],
 'population': ['3', '5', '2']}

In [133]:
df

country   capital population
0   belgia  brussels          3
1     indo       jkt          5
2  singapo   singapo          2

In [134]:
# pola buat tabelnya{'':[],'':[],'':[]}

### 2.1.3 Menambah kolom pada DataFrame

In [135]:
df.columns

Index(['country', 'capital', 'population'], dtype='object')

In [136]:
df['pop_2200']=np.nan

In [137]:
df

country   capital population  pop_2200
0   belgia  brussels          3       NaN
1     indo       jkt          5       NaN
2  singapo   singapo          2       NaN

In [139]:
df['bola']=np.nan

In [140]:
df

country   capital population  pop_2200  bola
0   belgia  brussels          3       NaN   NaN
1     indo       jkt          5       NaN   NaN
2  singapo   singapo          2       NaN   NaN

In [143]:
df['bola']=df['population']*2

In [144]:
df

country   capital population  pop_2200 bola
0   belgia  brussels          3       NaN   33
1     indo       jkt          5       NaN   55
2  singapo   singapo          2       NaN   22

## 2.2. Membaca File External dengan Pandas 

Dengan menggunakan Pandas atau numpy, kita dapat memuat data tabular dalam format csv kedalam project, dengan cara:

pd.read_csv(file_name, separator=',') atau np.genfromtxt(file_name, separator=',')

2.2 Slicing pada DataFrame 

Slicing dapat dilakuakan dengan beberapa cara:

cara Column and index slicing
Cara .iloc
cata `.loc'

In [154]:
df=pd.read_csv("file\cereal.csv");
df.head(5)

FileNotFoundError: [Errno 2] No such file or directory: 'file\\cereal.csv'

In [ ]:
df['name']

In [ ]:
df.name

In [ ]:
df[['name','fat']] #format yang digunakan adalah=  df[list of column]

In [ ]:
df[['name','fat']][10:20:2]

In [150]:
#datanya gak ada, coba cari format csv

In [151]:
#slicing dengan menggunakan conditional

Slicing dengan menggunakan conditional dapat dilakuakn dengan format seperti berikut:

df[cond]

dimana:

cond = df[column] == value

jika digabung:

df[df[column] == value]

In [ ]:
df[df['mfr'] =='N' ]
df[df['fiber'] > 5 ]
df[['name','fat']][df['mfr'] == 'N'].head(10)

## 2.3 Meng-update nilai pada Dataframe 

In [155]:
df['type'] = 'None Type'
df.head()

country   capital population  pop_2200 bola       type
0   belgia  brussels          3       NaN   33  None Type
1     indo       jkt          5       NaN   55  None Type
2  singapo   singapo          2       NaN   22  None Type

In [156]:
df.loc[0:3,'type']='type'
df.head()

country   capital population  pop_2200 bola  type
0   belgia  brussels          3       NaN   33  type
1     indo       jkt          5       NaN   55  type
2  singapo   singapo          2       NaN   22  type

In [157]:
df.loc[0:2,'type']='type'
df.head()

country   capital population  pop_2200 bola  type
0   belgia  brussels          3       NaN   33  type
1     indo       jkt          5       NaN   55  type
2  singapo   singapo          2       NaN   22  type

In [159]:
df['type'][0:3] = 'type 2'
df.head()

<ipython-input-159-7a6bdf21c7da>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['type'][0:3] = 'type 2'
C:\Users\Acer\miniconda3\envs\WS_GL_UP\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)


country   capital population  pop_2200 bola    type
0   belgia  brussels          3       NaN   33  type 2
1     indo       jkt          5       NaN   55  type 2
2  singapo   singapo          2       NaN   22  type 2

## 2.4 Mengubah Pandas menjadi Numpy Array 

In [160]:
df.values

array([['belgia', 'brussels', '3', nan, '33', 'type 2'],
       ['indo', 'jkt', '5', nan, '55', 'type 2'],
       ['singapo', 'singapo', '2', nan, '22', 'type 2']], dtype=object)

In [161]:
df.values[0:2]

array([['belgia', 'brussels', '3', nan, '33', 'type 2'],
       ['indo', 'jkt', '5', nan, '55', 'type 2']], dtype=object)

In [162]:
#kurang tau datanya gak bisa dikelola

In [163]:
#csv nya gak bisa dibuka

### 2.5 Menggunakan group by dan describe 

In [ ]:
df.groupby('mfr').count()
df.describe()

In [ ]:
#datanya gak bisa dibuka, cari latihan lain dalam format csv.